# Generated by Django 5.2.2 on 2025-06-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the property (e.g., '3 BHK Villa in Riverside')", max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the property features and amenities.')),
                ('property_type', models.CharField(choices=[('SALE', 'For Sale'), ('RENT', 'For Rent')], default='SALE', help_text='Is the property for sale or rent?', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the property (e.g., 5000000.00 for 50 Lakhs)', max_digits=15)),
                ('bedrooms', models.PositiveSmallIntegerField(default=1, help_text='Number of bedrooms.')),
                ('bathrooms', models.PositiveSmallIntegerField(default=1, help_text='Number of bathrooms.')),
                ('built_up_area', models.DecimalField(blank=True, decimal_places=2, help_text='Built-up area in Sq.Ft. (e.g., 1500.00)', max_digits=10, null=True)),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, help_text='Land area in cents (e.g., 5.50 cents). Only if applicable for land/villa.', max_digits=10, null=True)),
                ('location', models.CharField(help_text="Exact address or landmark, e.g., 'Near St. Mary's Church, Udayamperoor'", max_length=255)),
                ('amenities_proximity', models.TextField(blank=True, help_text="Comma-separated list of nearby amenities and their proximity (e.g., 'School: 1km, Hospital: 2km').", null=True)),
                ('main_image', models.ImageField(help_text='Main photo of the property.', upload_to='properties/')),
                ('image_1', models.ImageField(blank=True, help_text='Additional photo 1.', null=True, upload_to='properties/')),
                ('image_2', models.ImageField(blank=True, help_text='Additional photo 2.', null=True, upload_to='properties/')),
                ('image_3', models.ImageField(blank=True, help_text='Additional photo 3.', null=True, upload_to='properties/')),
                ('is_published', models.BooleanField(default=False, help_text='Check to make the property publicly visible.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the property was added.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp.')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
